### ISSUE TITLE
UX Enhancements

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent-gui#10]
There are some things which could make the experience a little bit cleaner:

- Default operation now is the first one listed in the Hydra Doc. Making the GET as default would be better to fast querying around Endpoints.

- Saving Operations State. Properties have their own state so you can go around and come back and the values will be there. States are lost when you switch endpoints.

- Button to clean properties. If you need to clean the form now you have to erase property by property.

These could be tackled one by one.

**Comment by PrathamDogra** [comment]
I would love to work on this issue.

**Comment by sudipt1999** [comment]
@PrathamDogra  are you working on it ! If not kindly let me know I will love to work on this one!
