### ISSUE TITLE
ModuleNotFoundError: No module named 'hydra_agent.agent

### ISSUE THREAD

**Issue by PrathamDogra** [HTTP-APIs/hydra-python-agent-gui#14]
I have successfully installed the requirements.txt using **python install -r requirements.txt**.
But on running **python app.py** a ModuleNotFoundError error is raised

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from hydra_agent.agent import Agent
ModuleNotFoundError: No module named 'hydra_agent.agent'

**Comment by Mec-iS** [comment]
have you added the project repo to `PYTHONPATH`.
The suggested way to run the software is using Docker, so to avoid to configure things manually.
