### ISSUE TITLE
IMPORTANT!! REDIS CONTAINER COMPROMISED

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-python-agent-gui#17]
See https://hub.docker.com/_/redis?tab=reviews for more information

**Comment by RishiDharshan** [comment]
HI I am new to the open source community ,
I would like to contribute to this project,
can anyone please point me to the right direction to contribute to this project

**Comment by Mec-iS** [comment]
you can join our Slack at hydraecosystem.slack.com

**Comment by Mec-iS** [comment]
should be fixed in the new container version
