### ISSUE TITLE
[FEAT] Docker 

### ISSUE THREAD

**Issue by hv7214** [HTTP-APIs/hydra-python-agent-gui#22]
**Checks**
- [x] I am running latest version.
- [x] This issue hasn't been filed yet by anyone.

**Details**
There should be docker config file. As without using docker issues are coming up like #14 .
It will be glad if i write the same.

**Current Environment**
Ubuntu 18.04, venv.

**Comment by Mec-iS** [comment]
As a design choice we would like to use Docker anywhere both to avoid longer installation procedures and avoid system versions incompatibilities. Beside the advantage for the students to learn a widely used tool.
