### ISSUE TITLE
Code restructuring 

### ISSUE THREAD

**Issue by dikshantj** [HTTP-APIs/hydra-python-agent-gui#24]
# I'm submitting a 
- [x] Code improvement

## Current Behaviour:
Currently the flask backend only contains a single file `app.py` which contains all its code. 

## Expected Behaviour:
Create a separate directory for the backend and to seperate helper functions from the main server file. 

## Do you want to work on this issue?
Yes

**Comment by dev-sankhadip** [comment]
I want to work on this issue, can i go ahead?

**Comment by xadahiya** [comment]
You don't need to ask for permission

**Comment by techieshashwat** [comment]
want to work on this issue

**Comment by SidharajYadav** [comment]
how i contribute on this 
please guide me

**Comment by Mec-iS** [comment]
use GitHub Pull Request
https://github.com/MarcDiethelm/contributing/blob/master/README.md
