### ISSUE TITLE
Getting error on  doing python3 app.py

### ISSUE THREAD

**Issue by aryamanpuri** [HTTP-APIs/hydra-python-agent-gui#25]
https://paste.mozilla.org/3nfZ8Uxq

**Comment by vedangj044** [comment]
Are u running any hydrus instance ??

See this [Issue](https://github.com/HTTP-APIs/hydra-python-agent-gui/issues/20)

**Comment by PrathamDogra** [comment]
@aryamanpuri are you running the docker image of redisgraph, if not then run
**sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.0-edge**

**Comment by SidharajYadav** [comment]
how i contribute on this project
