### ISSUE TITLE
Code Quality Improvement

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent-gui#45]
There are some Code-related improvements we could do on the repo:

- [X] Comply it with ESLint and add travis.yml to check it
- [ ] Add basic tests, front and backend
- [ ] React hooks

Other suggestions are welcome.

**Comment by sudipt1999** [comment]
I am working on it!

**Comment by vedangj044** [comment]
I am working on ESLint and travis.yml @sudipt1999

**Comment by sudipt1999** [comment]
@vedangj044 i am already working on the issue ! Can you please pick some other issue to work on !

**Comment by Guttz** [comment]
The PR covered part of the issue, feel free to contribute to the other bullet points.

**Comment by thrishik7** [comment]
@Guttz , I would like to work on the rest

**Comment by sudipt1999** [comment]
@thrishik7 I m already on it bro!

**Comment by king-11** [comment]
@Guttz does the 3rd point include changing from class components to functional for using hooks 🤔 ?

**Comment by king-11** [comment]
@Guttz any specific components or page I shall start with?

**Comment by king-11** [comment]
@Guttz sorry for not being active can you tell which components shall I start with also in the eslint config we can add plugins like
```import-export``` ```react-hooks``` for better linting any suggestions over that ?

**Comment by harshit-dugar** [comment]
Hi 
If this issue is not resolved I can help
I am new to this project @Guttz If you can guide me it will will a great help
