### ISSUE TITLE
Add graph interaction events/actions support

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent-gui#5]
We've used vis.js as our graphing library and it enables a range of events in its API. We can use this to make the user experience better. The basic idea would be populating the right form/buttons according to clicks in the nodes. But there's much more that could be done, the library enables hover, selection, doubleClick, dragging and etc. Link for the library events api: https://visjs.github.io/vis-network/docs/network/#Events

**Comment by thrishik7** [comment]
@Guttz , I would love to work on this

**Comment by sudipt1999** [comment]
@thrishik7 kindly let me know if you are working on this, I would love to work on this one!

**Comment by thrishik7** [comment]
@sudipt1999 , I have started working on hover and single click events . Maybe you can work on someother event/action. :)

**Comment by sudipt1999** [comment]
@thrishik7 okay great so i wish to work on dragging and popup part if thats ikay with you!

**Comment by thrishik7** [comment]
> @thrishik7 okay great so i wish to work on dragging and popup part if thats ikay with you!
@sudipt1999 , yeah sure please carry on.

**Comment by sudipt1999** [comment]
Sure @thrishik7  thanks !

**Comment by Guttz** [comment]
@thrishik7 Added click support for collections at https://github.com/HTTP-APIs/hydra-python-agent-gui/pull/40. Two ongoing tasks for this issue:

- I would suggest that the hover color modification should only happen on clickable nodes, not on every node.
- Another great addition would be click support for requests: If a click on a PUT Node that has a CommandCollection parent node, I could both set the collection and also the request type.

**Comment by thrishik7** [comment]
@Guttz , yeah I will continue working on it. 

> @thrishik7 Added click support for collections at #40. Two ongoing tasks for this issue:
> 
> * I would suggest that the hover color modification should only happen on clickable nodes, not on every node.
> * Another great addition would be click support for requests: If a click on a PUT Node that has a CommandCollection parent node, I could both set the collection and also the request type.

**Comment by Guttz** [comment]
Closing this for now. If someone has ideas for new graph interactions in the future, kindly open a new issue.
