### ISSUE TITLE
UI/Responsiveness 

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/hydra-python-agent-gui#51]
The GUI has a lot of great additions and new UX features that we would like to merge into the master branch. However, we need to solve this two small but important layout problems we added:

- For some reason the background of the graph is now white and not using the light gray that we have for the graph area
- The height is not really responsive and in a lot of screens due to some modifications right now we just have a white area below

Before:
![image](https://user-images.githubusercontent.com/11739405/77812266-f6618d80-707e-11ea-9336-d653f8f99e4c.png)

Now:
![image](https://user-images.githubusercontent.com/11739405/77812328-58ba8e00-707f-11ea-97da-222eb70c6940.png)

**Comment by vedangj044** [comment]
I am working on it 😊

**Comment by thrishik7** [comment]
@vedangj044 , if you dont mind can I work on the 2nd point, because Im almost done with it :)

**Comment by vedangj044** [comment]
@thrishik7 I was figuring out a way to do just that. But no problem, you can work on the 2nd point.

**Comment by sj00coder** [comment]
Sir,Is this issue is still open? I want to work on it. @Guttz

**Comment by khushishikhu** [comment]
@Guttz can I work on this issue

**Comment by Palaksharma23** [comment]
Is this issue still open ? 
Can I work on this issue ?.

**Comment by khareyash05** [comment]
@Guttz Changed background of hydra graph have a look!
