### ISSUE TITLE
GUI not rendering on browser

### ISSUE THREAD

**Issue by sameshl** [HTTP-APIs/hydra-python-agent-gui#58]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

I go to http://localhost:3000/, I don't see the agent. The agent does not get rendered.
This is what I see:
![image](https://user-images.githubusercontent.com/43701530/82429465-94833a00-9aa9-11ea-9ed2-2220b141f4f1.png)

### Expected Behaviour:

The agent should be rendered so I can interact with it as mentioned in the readme,
https://github.com/HTTP-APIs/hydra-python-agent-gui#hydra-agent-gui/
### Steps to reproduce:

Follow all steps in the [readme](https://github.com/HTTP-APIs/hydra-python-agent-gui/blob/master/README.md) to set up the agent and then visit http://localhost:3000/

**Comment by sameshl** [comment]
@xadahiya @chrizandr @Guttz Do you guys have any idea on how to solve this issue?
I am facing this from yesterday. @priyanshunayan and I have tried a lot to solve this but were not able to till now.

**Comment by priyanshunayan** [comment]
For now use this docker image:
1. Run hydrus using cli. i.e. `hydrus serve --no-auth`
2.  Run `sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.0-edge`
3.  Run `docker run --network="host" -P --rm priyanshunayan/agent-gui`

Note: This will not work for macOS as docker runs on different VM thus making local host unavailable for the container. I will create PR with a more robust solution. :)

**Comment by sameshl** [comment]
Thank you @priyanshunayan, the docker image works for now.

**Comment by chrizandr** [comment]
We also need to understand why it doesn't work without the docker image. Was there an error in the installation instructions? Or maybe some underlying bug in the codebase. Please research this further.

**Comment by sameshl** [comment]
Yes, @chrizandr. I research this further and try to find the root cause

**Comment by priyanshunayan** [comment]
I think #55 address this issue and solves it.
