### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by king-11** [HTTP-APIs/hydra-python-agent-gui#68]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

```pip3 install -r requirements.txt``` isn't working I have setup a clean virtualenv with py3.6.12

### Expected Behaviour:

should install

### Steps to reproduce:

![Screenshot_20210216_173715](https://user-images.githubusercontent.com/52061363/108061141-e4655080-707d-11eb-832c-eeade4ce0063.png)

### Do you want to work on this issue?

yes

**Comment by Mec-iS** [comment]
please search closed issues or ask on the Slack channel before opening a issue about installation problems.
