### ISSUE TITLE
Minor fixes in README file for hydra-python-agent-gui

### ISSUE THREAD

**Issue by crew-guy** [HTTP-APIs/hydra-python-agent-gui#71]
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
This is a minor issue in documentation where, in the README.md for hydra-python-agent-gui -

1. f of Flask should be capitalized in line no. 33 of README.md as shown in the image below:

<br/>
<br/>

![ss1](https://user-images.githubusercontent.com/69717009/110729584-fd0ff300-8244-11eb-865d-370fde82b716.png)

<br/>
2. The mention of the directory - console-frontend should be done as ```console-frontend```  all places for uniformity (line no. 45)

### Expected Behaviour:
Solving this bug will do 2 things

1. Make reading the README.md for hydra-python-agent-gui repo a lot better
2. Introduce me to the team managing this repository and contributing guidelines. This is the first of many PRs which I intend to create on this project

### Steps to reproduce:
Steps to reproduce this bug would be reversing everything suggested in this issue

1. Revert back uppercase F to lowercase f 

2. Revert back markdown highlighting on the console-frontend directory mentions i.e. replace all the ```console-frontend``` with console-frontend

### Do you want to work on this issue?
Yes

**Comment by yoBoyio** [comment]
Hello, I would like to work on this issue.
