### ISSUE TITLE
Error after running `apt-get install python3-venv`

### ISSUE THREAD

**Issue by adi611** [HTTP-APIs/hydra-python-agent-gui#91]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Error after running `apt-get install python3-venv`
![Screenshot from 2022-02-26 00-51-00](https://user-images.githubusercontent.com/50960175/155838735-261c8f64-8647-4cab-9e36-a74edb99277b.png)

### Expected Behaviour:

Python venv(virtual environment) should be installed successfully.

### Steps to reproduce:

Follow the instructions to install hydra-python-agent-gui and we get error after `apt-get install python3-venv`

### Do you want to work on this issue?

yes

**Comment by Mec-iS** [comment]
the error message explicitly says that you need to be `root` to run the command. This is basic Ubuntu/Linux knowledge.
